schedules:
- cron: "0 0 * * *"
  displayName: Daily Run
  branches:
    include:
      - main
  always: true
pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path

steps:
- task: GoTool@0
  displayName: "install Go"
  inputs:
    version: '1.22.0'
    goPath: '$(GOPATH)'
    goBin: '$(GOPATH)/bin'

- script: |
    go build .
  displayName: 'Get dependencies and build'

- task: AzureCLI@2
  displayName: 'Get data and upload'
  inputs:
    azureSubscription: 'aztfy-pmc-reader-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ./aztfy-download-counter -cosmosdb=$(COSMOSDB_ENDPOINT) -cosmoskey=$(COSMOSDB_KEY) -kusto-endpoint=$(PMC_KUSTO_ENDPOINT) -pmc-start-date=$(PMC_START_DATE)    
    useGlobalConfig: true
