schedules:
- cron: "0 0 * * *"
  displayName: Daily Run
  branches:
    include:
      - main
  always: true
pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path

steps:
- task: GoTool@0
  displayName: "install Go"
  inputs:
    version: '1.22.0'
    goPath: '$(GOPATH)'
    goBin: '$(GOPATH)/bin'

- script: |
    go build .
  displayName: 'Get dependencies and build'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'aztfy-pmc-reader-conn'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'
    useGlobalConfig: true

- script: |
    ./aztfy-download-counter
  workingDirectory: '$(modulePath)'
  displayName: 'Get data and upload'
  env:  
    COSMOSDB_ENDPOINT: $(COSMOSDB_ENDPOINT)
    COSMOSDB_KEY: $(COSMOSDB_KEY)
    PMC_KUSTO_ENDPOINT: $(PMC_KUSTO_ENDPOINT)
    PMC_START_DATE: $(PMC_START_DATE)